# Generated by Django 6.0.3 on 2026-03-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='session',
            name='auth_sessio_token_d2a7e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='auth_sessio_user_id_700f69_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='auth_user_email_ece7f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='auth_user_usernam_f2740e_idx',
        ),
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Адрес электронной почты пользователя (в качестве логина)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Указывает, может ли данный пользователь войти в систему.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Обязательно, не более 150 символов.', max_length=150, unique=True),
        ),
    ]
